[FIX] Remove duplicate TestCustomAllocatorSameSize test definition
The test was defined twice in TestLuaContextNewState.cpp:
- Line 37: correct location
- Line 320: duplicate removed

This fixes the build error: redefinition of TestLuaContextNewState_TestCustomAllocatorSameSize_Test

Signed-off-by: Jordan Vrtanoski <jordan.vrtanoski@gmail.com>